### ISSUE TITLE
Part of the progression

### ISSUE THREAD

**Issue by ogmon1243** [TheGangModpacks/Fun-in-the-Sky#2]
It would be cool if the end remastered mod with all its 12 different ender eyes could be made to spawn in different dimensions to make exploration necessary to get to the end. Dimensions can include the twilight forest, beneath, nether, atum, and the 2 blue skies dims. 2 eyes in each dim would make all 12 required. Maybe a data pack could be used to change the spawn locations.

**Comment by FooterMan14** [comment]
I'll add the mods and check it out. Thanks for the suggestion.

**Comment by FooterMan14** [comment]
Twilight Forest will not be added at this time.
