### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by FooterManDev** [TheGangModpacks/Fun-in-the-Sky#20]
Current known issues will be documented here. Please check this issue thread before posting your issue.

**Comment by FooterMan15** [comment]
Now the UI in some menus is forced to GUI level 3 to mitigate the issue.

**Comment by FooterManDev** [comment]
When clicking Grass Blocks with Tools, the Tool will be deleted. Along with this, Grass can just be clicked at random, which shouldn't happen.
