### ISSUE TITLE
how to fix ex nihilo

### ISSUE THREAD

**Issue by remplerus** [TheGangModpacks/Fun-in-the-Sky#21]
**Modpack Version** alpha 0.0.2

fix for exnihilo

use this link to see, what u did wrong:
https://github.com/TheGangModpacks/Fun-in-the-Sky/blob/ef11315ac16767ded245e1711746e35f648a52bb/kubejs/server_scripts/general/Common/shaped/vanilla.js#L39

**Comment by FooterManDev** [comment]
Fixed up, thank you for pointing out.
