### ISSUE TITLE
crafting and getting stack of item instead of proper amount

### ISSUE THREAD

**Issue by iceman0769** [TheGangModpacks/Fun-in-the-Sky#26]
**Modpack Version**
0.0.7

**Describe the bug**
when crafting with mats for single item right clicking out of grid gives stack instead of single item

**To Reproduce**

**Expected behavior**

**Extras**
Additional context, screenshots, etc.

**Comment by ogmon1243** [comment]
This is an issue with the new update of fast workbench. Its been a problem in other packs.

**Comment by FooterManDev** [comment]
Thank you for reporting. We have downgraded the mod for now.
