### ISSUE TITLE
Recursive recipe needs

### ISSUE THREAD

**Issue by Blees-o-tron** [TheGangModpacks/Fun-in-the-Sky#43]
Steel Casing (Mek) requires Reactor Glass (Mek), which requires Enriched Iron (Mek), which requires Metallurgic Infuser (Mek), which requires Steel Casing.

**Comment by FooterManDev** [comment]
I have confirmed in-dev, and will make a fix.

**Comment by FooterManDev** [comment]
I totally made this sound like a bug report 😐
The recipe sucks, and I'll change it.

**Comment by FooterManDev** [comment]
Recipe now uses Structural Glass instead. I must warn you, Mekanism is not fully configured yet, everything is subject to change. Just keep that in mind, as you might get entangled in unwanted Quest twine.
