### ISSUE TITLE
[BUG] Creating andesite pebbles from andesite consumes hammer

### ISSUE THREAD

**Issue by Hoff2567** [TheGangModpacks/Fun-in-the-Sky#46]
### Is this a client or server issue?

Client

### Modpack Version

0.1.5

### Bug Description

Creating andesite pebbles by shift-right clicking on andesite with a hammer consumes the hammer, and quite often at that.

### Steps To Reproduce

Shift-right click on andesite with a hammer.

### Expected Behavior

Hammer to take durability but not be consumed.

**Comment by FooterManDev** [comment]
This is a known issue that I should have fixed already. I apologize for the issue.

**Comment by Hoff2567** [comment]
All good just didn't see it on the tracker, figured I'd pop it on.

**Comment by FooterManDev** [comment]
I've decided to remove the Andesite Pebble recipe entirely. There's not really any reason for it to exist.
Thank you for the report.
